# Generated by Django 5.2.5 on 2025-10-15 15:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_preset',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.booking_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_datetime',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('done', 'Erledigt'), ('cancelled_customer', 'Storniert (Kunde)'), ('cancelled_admin', 'Storniert (Admin)')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('electric', 'Elektrik'), ('plumbing', 'Sanitär'), ('furniture', 'Möbel'), ('appliance', 'Geräte'), ('other', 'Sonstiges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_estimate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(default='Std.', max_length=50),
        ),
    ]
