# Generated by Django 5.2.5 on 2025-10-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buchung', 'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bewertung', 'verbose_name_plural': 'Bewertungen'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Potsdam', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_datetime',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_preset',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('confirmed', 'Bestätigt'), ('done', 'Erledigt'), ('cancelled', 'Storniert')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('appliance', 'Appliance / Geräteinstallation'), ('electric', 'Electric / Elektrik'), ('furniture', 'Furniture / Möbel'), ('plumbing', 'Plumbing / Sanitär'), ('other', 'Other / Sonstiges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=6),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(default='Std.', max_length=20),
        ),
    ]
