# Generated by Django 5.2.5 on 2025-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gearbeitete Stunden', max_digits=5, null=True),
        ),
    ]
