# Generated by Django 5.2.5 on 2025-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gefahrene Kilometer (einfach)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Fahrzeit in Minuten (hin+zurück)', null=True),
        ),
    ]
